id: ADECCCCA0
base_file: f1F81.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.481762
  last_modified_at: 2022-06-19 17:56:06.481765
