id: ADECCCCA0
base_file: fCF4C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.505620
  last_modified_at: 2022-06-19 17:56:06.505623
