id: ADECCCCA0
base_file: f0E33.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.480711
  last_modified_at: 2022-06-19 17:56:06.480716
