id: ADECCCCA0
base_file: f517C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.489740
  last_modified_at: 2022-06-19 17:56:06.489755
