id: ADECCCCA0
base_file: f66B3.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.496215
  last_modified_at: 2022-06-19 17:56:06.496223
