id: ADECCCCA0
base_file: f9F43.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.503047
  last_modified_at: 2022-06-19 17:56:06.503050
