id: ADECCCCA0
base_file: f8166.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.501062
  last_modified_at: 2022-06-19 17:56:06.501065
