id: ADECCCCA0
base_file: f0B01.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.478807
  last_modified_at: 2022-06-19 17:56:06.478815
