id: ADECCCCA0
base_file: f83B2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.502037
  last_modified_at: 2022-06-19 17:56:06.502040
