id: ADECCCCA0
base_file: f3384.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:06.483406
  last_modified_at: 2022-06-19 17:56:06.483411
